# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
          backend: ${{ steps.filter.outputs.backend }}
          frontend: ${{ steps.filter.outputs.frontend }}
#     defaults:
#          run:
#              working-directory: "./src/main/java/com/dalcho/adme"

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
#     - uses: dorny/paths-filter@v2
#       id: filter
#       with:
#           filters: |
#             backend:
#               - './src/main/java/com/dalcho/adme/**'
#             frontend:
#               - './src/main/resources/static/**'
        
    - name: Grant execute permission for gradlew (빌드 전 gradle 권한 부여)
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#       with:
#         arguments: build
        # test 제외 코드
      #run : ./gradlew clean build --exclude-task test
        
    - name: Cache (Gradle 파일 캐싱)
      uses: actions/cache@v3.2.6
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
